In [2]:
import torch

/home/ntguest/.local/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
print(torch.__version__)

2.7.0+cu126


In [4]:
scalar = torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Turn Scalar into an integer
scalar.item()

7

In [8]:
scalar.float()

tensor(7.)

In [9]:
vector = torch.tensor([1,2,3])

In [10]:
vector

tensor([1, 2, 3])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([3])

In [13]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
random_tensor = torch.rand(3,4)

In [16]:
random_tensor

tensor([[0.6230, 0.5944, 0.6893, 0.3902],
        [0.4931, 0.0961, 0.4339, 0.9974],
        [0.5350, 0.1846, 0.7633, 0.5567]])

In [17]:
randomer_tensor = torch.rand(3,4,5)

In [18]:
randomer_tensor

tensor([[[0.2128, 0.8964, 0.5298, 0.3847, 0.6876],
         [0.8181, 0.5461, 0.7837, 0.8477, 0.9692],
         [0.0708, 0.8817, 0.6553, 0.3156, 0.5617],
         [0.5421, 0.3773, 0.6598, 0.7242, 0.6840]],

        [[0.2904, 0.5850, 0.3211, 0.9954, 0.9411],
         [0.7676, 0.0648, 0.7794, 0.9324, 0.5587],
         [0.1452, 0.2928, 0.1229, 0.5082, 0.5610],
         [0.6537, 0.0344, 0.4372, 0.2260, 0.7882]],

        [[0.1478, 0.3198, 0.2276, 0.9310, 0.9783],
         [0.9128, 0.0235, 0.0717, 0.3330, 0.3285],
         [0.3998, 0.5033, 0.5257, 0.5468, 0.4784],
         [0.5922, 0.6599, 0.2530, 0.1543, 0.8812]]])

In [19]:
randomer_tensor.shape

torch.Size([3, 4, 5])

In [20]:
randomer_tensor.dtype

torch.float32

In [21]:
randomer_tensor.device

device(type='cpu')

In [22]:
matrix1 = torch.rand(3,4)
matrix2 = torch.rand(4,3)
matrix3 = torch.matmul(matrix1, matrix2)


In [23]:
matrix4 = matrix1 @ matrix2

In [24]:
matrix4

tensor([[1.2332, 1.8667, 1.8674],
        [0.7894, 1.2996, 1.1051],
        [0.9530, 1.4281, 1.2776]])

In [25]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1,2,3])

In [26]:
t3 = t1 @ t2
t3

tensor(14)

In [27]:
t1 * t2

tensor([1, 4, 9])

# Operations

In [28]:
x = torch.arange(0,10,100)

In [29]:
x.min()

tensor(0)

In [30]:
x.max()

tensor(0)

In [31]:
x.type(torch.float32).mean()

tensor(0.)

# Tensor Operations

In [32]:
random_tensor = torch.rand(size=(3,4))

In [33]:
random_image_size = torch.rand(size=(224,224,3))

In [34]:
random_image_size.shape, random_image_size.ndim

(torch.Size([224, 224, 3]), 3)